# Tratamiento de imágenes y vídeos con OpenCV

<b>Fuentes:</b> 
1. [Tutoriales oficiales de OpenCV](https://docs.opencv.org/4.x/d6/d00/tutorial_py_root.html)
2. Joseph Howse and Joe Minichino, [Learning OpenCV 4 Computer Vision with Python3](https://learning-oreilly-com.bibproxy.ulpgc.es/library/view/learning-opencv-4/9781789531619/), Packt, 2020 (accesible en O'Reilly)
3. [OpenCV Course - Full Tutorial with Python](https://www.youtube.com/watch?v=oXlwWbU8l2o)


## Gestión de imágenes y vídeos

Lectura y escritura de imágenes y vídeos desde fichero y webcam.

In [1]:
#Lectura y Escritura de imágenes
import cv2 as cv

img = cv.imread('images/eii.png')

#cv.imwrite('images/eii2.png', img)



In [3]:
# lectura de imágenes
import cv2 as cv
#import numpy as np

file = 'images/eii.png'
#image = cv.imread(file) #,cv.IMREAD_GRAYSCALE)
image = cv.imread(file,cv.IMREAD_GRAYSCALE)

cv.imshow('EII', image)

k = cv.waitKey(0)

if k==ord('s'):
    print('Guardamos la imagen')
    cv.imwrite('images/eiiprueba.png', image)

cv.destroyAllWindows()


In [4]:
# lectura de vídeos
import cv2 as cv
video = cv.VideoCapture('videos/times-square.mp4')

while True:
    state, frame = video.read()
    
    cv.imshow('Video', frame)
    
    if cv.waitKey(20)==27:
        break

video.release()
cv.destroyAllWindows()


In [5]:
# lectura de webcam
import cv2 as cv

video = cv.VideoCapture(0)

while True:
    state, frame = video.read()
    
    cv.imshow('Video', frame)
    
    if cv.waitKey(20)==27:
        break

video.release()
cv.destroyAllWindows()

## Dibujo de primitivas
1. Líneas
2. Rectángulos
3. Círculos
4. Elipses
5. Polígonos
6. Texto


In [7]:
#Dibujando primitivas
import cv2 as cv
import numpy as np

w = 300
h = 50

image = cv.imread('images/eii.png')
cv.circle(image, (w,h), 25, (0,0,255), thickness=cv.FILLED)
#cv.line(image, (0,0), (500,100), (0,255,0), thickness=4)

cv.imshow('Punto',image)
#cv.imshow('Línea',image)

cv.waitKey(0)
cv.destroyAllWindows()



In [8]:
#Dibujando primitivas
import cv2 as cv
import numpy as np

image = cv.imread('images/eii.png')

w = image.shape[1]//2
h = image.shape[0]//2

cv.line(image, (0,0), (w,h), (0,255,0), thickness=4)

cv.rectangle(image, (w,h), (w*2-30,h*2-30), (255,128,0), thickness=cv.FILLED)

cv.circle(image, (w,h), 50, (255,0,0), thickness=2)

cv.ellipse(image, (w//2,h),(100,50),45,0,360,(100,100,100),-1)

cv.putText(image, "Centro", (w,h), cv.FONT_HERSHEY_SIMPLEX, 1, (0,200,200), 2, cv.LINE_AA)

pts = np.array([[w+10,50],[w-25,85],[w+40,100],[w+140,80],[w+100,60]], np.int32)
print(pts)
pts = pts.reshape((-1,1,2))
print('***')
print(pts)
cv.polylines(image,[pts],True,(0,0,0),3)

cv.imshow('Primitivas',image)

cv.waitKey(0)
cv.destroyAllWindows()



[[236  50]
 [201  85]
 [266 100]
 [366  80]
 [326  60]]
***
[[[236  50]]

 [[201  85]]

 [[266 100]]

 [[366  80]]

 [[326  60]]]


## Interacción con el usuario
1. Uso de *trackbars*
2. Uso del ratón

In [ ]:
# Uso de un trackbar
import cv2 as cv

def trackbar(x):
    print(x)
    #cv.imshow('EII', img)

img = cv.imread('images/eii.png', cv.IMREAD_COLOR)
cv.imshow('EII', img)
cv.createTrackbar('x', 'EII', 100, 255, trackbar)
cv.waitKey(0)
cv.destroyAllWindows()

In [ ]:
import cv2 as cv

# Uso de varios Trackbars
def trackbar(x):
    x = cv.getTrackbarPos('x', 'EII')
    y = cv.getTrackbarPos('y', 'EII')
    print(x,y)
    cv.imshow('EII', img)

img = cv.imread('images/eii.png')
cv.imshow('EII', img)

cv.createTrackbar('x', 'EII', 100, 255, trackbar)
cv.createTrackbar('y', 'EII', 100, 255, trackbar)

cv.waitKey(0)
cv.destroyAllWindows()


In [ ]:
import cv2 as cv

# Uso de varios Trackbars
def nothing(x):
    pass
   
img = cv.imread('images/eii.png')
cv.imshow('EII', img)

cv.createTrackbar('x', 'EII', 100, 255, nothing)
cv.createTrackbar('y', 'EII', 100, 255, nothing)

#cv.setTrackbarPos('x', 'EII', 111)
#cv.setTrackbarPos('y', 'EII', 222)


while True:
    cv.imshow('EII', img)   
    k = cv.waitKey(1)
    if k == 27:
        break
    x = cv.getTrackbarPos('x', 'EII')
    y = cv.getTrackbarPos('y', 'EII')
    print(x,y)
    
cv.destroyAllWindows()

In [2]:
import numpy as np
import cv2 as cv
 
def nothing(x):
    pass
 
# Create una imagen negra en una ventana
img = np.zeros((300,512,3), np.uint8)
cv.namedWindow('image')
 
# crear trackbars para cambio de color
cv.createTrackbar('R','image',0,255,nothing)
cv.createTrackbar('G','image',0,255,nothing)
cv.createTrackbar('B','image',0,255,nothing)
 
# crear un interruptor para funcionalidad ON/OFF
switch = '0 : OFF \n1 : ON'
cv.createTrackbar(switch, 'image',0,1,nothing)
 
while(1):
    cv.imshow('image',img)
    k = cv.waitKey(1) & 0xFF
    if k == 27:
        break
 
    # Optener estado actual de los cuatro trackbacks
    r = cv.getTrackbarPos('R','image')
    g = cv.getTrackbarPos('G','image')
    b = cv.getTrackbarPos('B','image')
    s = cv.getTrackbarPos(switch,'image')
 
    if s == 0:
        img[:] = 0
    else:
        img[:] = [b,g,r]
 
cv.destroyAllWindows()

In [3]:
# Uso del ratón
import cv2 as cv
import numpy as np

def mouse(event, x, y, flags, param):
    text = f'{event} - ({x}, {y}), flags={flags}, param={param}'
    print(text)
    if flags==1:
        #img[y-1,x]=[255,0,0]
        #img[y,x]  =[255,0,0]
        #img[y+1,x]=[255,0,0]
        #img[y,x-1]=[255,0,0]
        #img[y,x+1]=[255,0,0]
        
        img[y-1,x]=[0,255,0]
        img[y,x]  =[0,255,0]
        img[y+1,x]=[0,255,0]
        img[y,x-1]=[0,255,0]
        img[y,x+1]=[0,255,0]
     
        #img[y-1,x]=[0,0,255]
        #img[y,x]  =[0,0,255]
        #img[y+1,x]=[0,0,255]
        #img[y,x-1]=[0,0,255]
        #img[y,x+1]=[0,0,255]
        
    cv.imshow('EII', img)

img = cv.imread('images/eii.png')
#img = 255*np.ones((480,640,3), np.uint8)

cv.imshow('EII', img)

cv.setMouseCallback('EII', mouse)

cv.waitKey(0)
cv.destroyAllWindows()

0 - (121, 13), flags=0, param=None
0 - (161, 52), flags=0, param=None
0 - (213, 94), flags=0, param=None
0 - (272, 131), flags=0, param=None
0 - (278, 134), flags=0, param=None
0 - (301, 146), flags=0, param=None
0 - (303, 147), flags=0, param=None
0 - (309, 149), flags=0, param=None
0 - (311, 150), flags=0, param=None
0 - (313, 151), flags=0, param=None
0 - (313, 152), flags=0, param=None
0 - (314, 153), flags=0, param=None
0 - (314, 154), flags=0, param=None
0 - (315, 155), flags=0, param=None
0 - (315, 157), flags=0, param=None
0 - (315, 160), flags=0, param=None
0 - (316, 163), flags=0, param=None
0 - (316, 166), flags=0, param=None
0 - (316, 167), flags=0, param=None
0 - (315, 171), flags=0, param=None
0 - (312, 173), flags=0, param=None
0 - (307, 176), flags=0, param=None
0 - (306, 176), flags=0, param=None
0 - (296, 180), flags=0, param=None
0 - (294, 180), flags=0, param=None
0 - (282, 185), flags=0, param=None
0 - (281, 186), flags=0, param=None
0 - (270, 190), flags=0, param=

IndexError: index 363 is out of bounds for axis 0 with size 363

0 - (361, 366), flags=1, param=None


IndexError: index 365 is out of bounds for axis 0 with size 363

4 - (361, 366), flags=1, param=None


IndexError: index 365 is out of bounds for axis 0 with size 363

0 - (356, 362), flags=0, param=None
0 - (355, 361), flags=0, param=None
0 - (355, 360), flags=0, param=None
0 - (354, 358), flags=0, param=None
0 - (353, 357), flags=0, param=None
0 - (353, 354), flags=0, param=None
0 - (369, 345), flags=0, param=None
0 - (374, 342), flags=0, param=None
0 - (380, 341), flags=0, param=None
0 - (430, 333), flags=0, param=None
0 - (448, 245), flags=0, param=None
0 - (442, 243), flags=0, param=None
0 - (437, 240), flags=0, param=None
0 - (433, 238), flags=0, param=None
0 - (416, 229), flags=0, param=None
0 - (402, 221), flags=0, param=None
0 - (396, 217), flags=0, param=None
0 - (396, 216), flags=0, param=None
0 - (394, 213), flags=0, param=None
0 - (393, 208), flags=0, param=None
0 - (392, 207), flags=0, param=None
0 - (392, 203), flags=0, param=None
0 - (391, 199), flags=0, param=None
0 - (390, 196), flags=0, param=None
0 - (390, 195), flags=0, param=None
0 - (390, 192), flags=0, param=None
0 - (390, 189), flags=0, param=None
0 - (390, 185), flags=0, par

In [ ]:
#Trackbar para cambiar un eje de color
import cv2 as cv #BGR
import numpy as np

def trackbar(x):
    img[:, :, 2] = x
    cv.imshow('Mapa de Colores', img)

img = np.zeros((256, 256, 3), dtype=np.uint8)
for i in range(256):
    img[i, :, 0] = i
    img[:, i, 1] = i
    
cv.imshow('Mapa de Colores', img)

cv.createTrackbar('red', 'Mapa de Colores', 0, 255, trackbar)

cv.waitKey(0)
cv.destroyAllWindows()